### ISSUE TITLE
maven 下载不下来啊什么情况

### ISSUE THREAD

**Issue by HaiTao-G** [duanxinyuan/Json-Utils#5]
Could not transfer artifact com.github.duanxinyuan:json-jackson:pom:1.8.0 from/to repo1 (http://repo1.maven.org/maven2/): Transfer failed for http://repo1.maven.org/maven2/com/github/duanxinyuan/json-jackson/1.8.0/json-jackson-1.8.0.pom 501 HTTPS Required

**Comment by duanxinyuan** [comment]
之前贴的版本错了，用1.0.0吧，这是中央仓库地址：https://repo1.maven.org/maven2/com/github/duanxinyuan/json-jackson/1.0.0/

**Comment by G-H-Tao** [comment]
java: 无法访问com.dxy.library.json.jackson.JacksonUtil
  错误的类文件: /F:/JAR/Repository/com/github/duanxinyuan/json-jackson/1.0.0/json-jackson-1.0.0.jar!/com/dxy/library/json/jackson/JacksonUtil.class
    类文件具有错误的版本 58.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by HaiTao-G** [comment]
@duanxinyuan java: 无法访问com.dxy.library.json.jackson.JacksonUtil
  错误的类文件: /F:/JAR/Repository/com/github/duanxinyuan/json-jackson/1.0.0/json-jackson-1.0.0.jar!/com/dxy/library/json/jackson/JacksonUtil.class
    类文件具有错误的版本 58.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。
还是不能使用的

**Comment by duanxinyuan** [comment]
忘了我本地的JDK是14了，我降低下jdk版本重新deploy一下

**Comment by duanxinyuan** [comment]
发布好了：https://repo1.maven.org/maven2/com/github/duanxinyuan/json-utils/1.1.0/
