### ISSUE TITLE
依赖的json-utils下载不下来

### ISSUE THREAD

**Issue by HaiTao-G** [duanxinyuan/Json-Utils#6]
Could not find artifact com.github.duanxinyuan:json-utils:jar:1.0.0 in alimaven (http://maven.aliyun.com/nexus/content/groups/public/)

**Comment by duanxinyuan** [comment]
maven地址配置里，加一个maven中央仓库的Profile就可以了，maven中央仓库有文件的：https://repo1.maven.org/maven2/com/github/duanxinyuan/json-utils/1.0.0/

**Comment by duanxinyuan** [comment]
1.0.0版本的JDK是14，可以用1.1.0：https://repo1.maven.org/maven2/com/github/duanxinyuan/json-utils/1.1.0/
